# Generated by Django 5.1.2 on 2024-10-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_empresa_jogo_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='empresa',
        ),
    ]
