# Generated by Django 5.1.2 on 2024-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_usuario_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='conta',
            field=models.FloatField(default=1000),
        ),
    ]
