# Generated by Django 5.1.4 on 2024-12-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_usuario_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usuario')),
            ],
        ),
    ]
